# Generated by Django 5.2.8 on 2025-11-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_profile_user_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
