# Generated by Django 5.2.8 on 2025-11-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_alter_profile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
