# Generated by Django 5.2.8 on 2025-11-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_bookmark_postmedia_valid_media_type_bookmark_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to='social_media.post'),
        ),
    ]
